services:
  puppeteer-app:
    build:
      context: .
      dockerfile: Dockerfile
    user: root
    volumes:
      - ./data:/home/pptruser/app/data
    ports:
      - "3000:3000"
    environment:
      - PUPPETEER_CACHE_DIR=/home/pptruser/.cache/puppeteer
    command: ["node", "--experimental-modules", "server.js"]
    cap_add:
      - SYS_ADMIN
    mem_limit: 3g
    mem_reservation: 1g
    cpus: 0.8
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 3G
          cpus: '0.8'
        reservations:
          memory: 1G
          cpus: '0.4'
      update_config:
        order: start-first
        failure_action: rollback
        delay: 10s
      rollback_config:
        parallelism: 0
        order: stop-first
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
